### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Harbs** [jimojon/Multipart.as#9]
Thanks for a great class!

It does not look like you've specified the license of this code.

I have two questions:
1. What are the license terms?
2. Would you consider allowing Apache Flex to adopt this class?

**Comment by jimojon** [comment]
Hello Harbs,

1. Just added an Apache 2.0 license
2. With pleasure :)

Jonas

**Comment by Harbs** [comment]
Awesome.

**Comment by aharui** [comment]
Can you put the standard Apache Licensing header in the Multipart.as file?  It makes it easier for us to track.  See: http://www.apache.org/licenses/LICENSE-2.0#apply

**Comment by aharui** [comment]
Also, it appears there are 3 other people who contributed code to Multipart.as.  Do you have any sort of contributors agreement with them that pre-approves using the Apache License?  If not, you may need to ask them for approval.

**Comment by jimojon** [comment]
Hello @normanzb, @Nek- and @zlumer,
I just added an Apache 2.0 to this project to enable its use by Apache Flex.
After talking with @aharui it appears that, as a contributor, you must approve this addition.
Are you ok for that ?
Thanks !

**Comment by zlumer** [comment]
I'm okay with any permissive license (no restrictions for end user to use this code in a commercial project, etc.). GPL is NOT good, Apache/CC is nice.

**Comment by normanzb** [comment]
I am fine with it! actually I replied in a separate mail for that as well

**Comment by Nek-** [comment]
Ok to me no problem.

**Comment by jimojon** [comment]
Thanks to all!
@aharui : I just added the header and every contributors are ok.
